### ISSUE TITLE
Not all errors write the .werr file

### ISSUE THREAD

**Issue by greschd** [wannier-developers/wannier90#142]
In trying to find an easy way to detect a failed Wannier90 run, I discovered that an error does not always mean a ``.werr`` is created. An example of this is when the number of overlaps in the ``.mmn`` file does is not correct.

Is this behaviour on purpose, or should the error file always be written when an error occurs? A workaround for detecting the failed runs is to just look for the ``Exiting.......`` string in the output.

**Comment by mostofi** [comment]
Hi Dominik

I don’t think this is intentional - we have tried in so far as possible to handle errors by calling io_error, which should write a message to the .werr file. Looking at overlap.F90, this is also what should happen when there is a problem reading the mmn file…

Best wishes,

Arash

—
Arash Mostofi — www.mostofigroup.org<http://www.mostofigroup.org>
Director, CDT in Theory and Simulation of Materials
Imperial College London



On 27 Jul 2017, at 09:44, Dominik Gresch <notifications@github.com<mailto:notifications@github.com>> wrote:


In trying to find an easy way to detect a failed Wannier90 run, I discovered that an error does not always mean a .werr is created. An example of this is when the number of overlaps in the .mmn file does is not correct.

Is this behaviour on purpose, or should the error file always be written when an error occurs? A workaround for detecting the failed runs is to just look for the Exiting....... string in the output.

**Comment by greschd** [comment]
Ok, I'll try to investigate why the ``.werr`` file doesn't appear in the sample case I had. Can you please assign the issue to me?

**Comment by greschd** [comment]
The problem is that ``io_error`` writes to the ``stdout`` unit in the non-MPI code [(see here)](https://github.com/wannier-developers/wannier90/blob/develop/src/io.F90#L244). In ``wannier_prog.F90``, ``stdout`` is set to the ``.werr`` file during ``param_read``, but later set to the ``.wout`` file [(here)](https://github.com/wannier-developers/wannier90/blob/develop/src/wannier_prog.F90#L95).

So this means that if there are errors within reading the parameters list, the errors are written to ``.werr``, but otherwise not.

I believe the correct way to solve this would be to add a ``stderr`` file unit which always points to the ``.werr`` file, and then use that. In the MPI code, we would have to rename the file units for each node (now called ``stderr``).

@mostofi, what do you think about this?

**Comment by giovannipizzi** [comment]
While this is important, we're moving it to v3.1 while we are feature-freezing the code for 3.0

**Comment by mikibonacci** [comment]
Testing on `develop` branch seems to have the error correctly written in the `.werr` file. 

I tested the `examples/example03` by removing randomly some lines in the `silicon.mmn` file, or changing the number of bands or kpoints in the same file. I also tried to change the number of bands in the `silicon.win` file. Every time, the `silicon.werr` is generated with the correct error reported.

@greschd could you test again with the last `develop`?

**Comment by greschd** [comment]
Hi @mikibonacci,

Thanks for looking into this. Unfortunately, I don't have access to the original error case anymore. The tests you've made seem reasonable to me, so I think it's fine to just close this issue.
