### ISSUE TITLE
Error in large parallel runs

### ISSUE THREAD

**Issue by jryates** [wannier-developers/wannier90#171]
Error reported to developers whereby Wannier90 crashes in wannierise routines when run in parallel for largest (ish) systems

**Comment by hjunlee** [comment]
Dear Prof. Jonathan R. Yates:

This has already been discussed in my previous commit:
https://github.com/wannier-developers/wannier90/pull/120

The main source of this problem is that currently most of the data (large matrices) is not distributed. In my personal version, I worked around this problem partially.

If you want, I will align the part of the subroutines to the current version of Wannier90 and submit them.

Sincerely,

Hyungjun Lee
EPFL

**Comment by jryates** [comment]
I think your earlier comment referred to postw90, and this is the main wannier90 - but I wouldn't be surprised if this was the same issue. I know that I need to take the time to think about how memory is managed within the code.
 As well as other changes, it would make a lot of sense to make use of shared memory using something like Ian Bush's FreeIPC.f90
 If you have time to update your code to the latest version, I would be happy to take a look.
Thanks!

**Comment by hjunlee** [comment]
Dear Prof. Jonathan R. Yates:

I submitted the part of modifications done in my personal version (https://github.com/wannier-developers/wannier90/pull/173).
They are related to the distribution of large matrices in W90.
u_matrix and u_matrix_opt are also possible, but I didn't apply in this commit since it is more complex to align it into the recent version of W90 than I expected.

I am not sure whether this can solve the problem you mentioned since I don't know the problem.
But, this can solve some cases which lead to the memory shortage.

PS)
>As well as other changes, it would make a lot of sense to make use of shared memory using >something like Ian Bush's FreeIPC.f90

It is very interesting! Thank you for the info.

Sincerely,

Hyungjun Lee
EPFL
