### ISSUE TITLE
Trailing Whitespace

### ISSUE THREAD

**Issue by jryates** [wannier-developers/wannier90#190]
From: @jimustafa and pull-request #189 
"This brings up the question of how to deal with whitespace. It is common practice to exclude trailing whitespace, usually by configuring the text editor to trim whitespace upon saving. Perhaps it is desirable to trim trailing whitespace throughout the codebase and implement whitespace checking as part of accepting a pull request."

**Comment by giovannipizzi** [comment]
From a quick check, this looks like it's a good tool: https://pypi.org/project/fprettify/

If you agree @jryates @mostofi I will implement it in a test, and prepare a pre-commit hook, that can be installed locally, so that before committing the tool is run automatically for you (very easy to use).

Only thing to check would be to see if the FORD documentation is not "disrupted" but I don't think so, by default it only changes indentation/whitespaces.

**Comment by giovannipizzi** [comment]
Long lines are apparently not supported, but we can replace
```
write(*,*) "aa&
  &bb"
```
with
```
write(*,*) "aa" // &
  "bb"
```
The plan is to wait that major PRs are merged, and then to try to apply this and see if there is no problem. Will be done in the next coding day.

**Comment by giovannipizzi** [comment]
I also found this: https://github.com/dev-zero/f90-formatter
I think both are used by CP2K, I'll ask dev-zero (Tiziano Müller) what they suggest

**Comment by pseewald** [comment]
@giovannipizzi 
The above link is an old fork of this repository:
https://github.com/pseewald/fprettify

You found this already on PyPi but currently only the github version is up to date (sorry, I will soon update PyPi release...).

CP2K uses fprettify and additionally a script for more aggressive formatting (removal of unused variables and sorting/reordering of variables and use statements). I don't recommend using the CP2K script since many of the formatting choices are CP2K-specific, also it is quite buggy, not maintained and will conflict with FORD.

If you give fprettify a try, please let me know if you encounter any problems.
