### ISSUE TITLE
Is it meaningfuul to SVD a number ? u_matrix(1,1,nkp) in overlap_project()

### ISSUE THREAD

**Issue by algorithmx** [wannier-developers/wannier90#225]
https://github.com/wannier-developers/wannier90/blob/d4a245564808e3a00136731262f61cc5ec948f51/src/overlap.F90#L665

I think it should be `u_matrix( : , : , nkp )` instead of `u_matrix( 1 , 1 , nkp )`, otherwise the following code is not meaningfuul. Could someone defend this line by explaining the meaning ?

**Comment by giovannipizzi** [comment]
This should be equivalent (even if possibly less clear), since the version with (1,1,nkp) points to the first location in memory of the u_matrix array at given nkp (and in fortran the last index is the slowest), that is what the ZGESVD expects as a parameter (the size is passed in the previous parameters, `num_bands`.

**Comment by algorithmx** [comment]
that is clear, thank you !
