### ISSUE TITLE
Minor typo in slwf_num vs. num_wann check

### ISSUE THREAD

**Issue by AAlMutairi** [wannier-developers/wannier90#261]
Hello everyone,

According to the user manual in page 37, slwf_num should be less than or equal to num_wann. However, in line 821 in Parameters.F90 it states:

if (slwf_num .lt. num_wann) selective_loc = .true.

I believe it should be replaced with

if (slwf_num .le. num_wann) selective_loc = .true.

Thank you,
AbdulAziz AlMutairi

**Comment by VVitale** [comment]
This is more a typo in the manual than a mistake in the code. The reason is that you can only selectively localise a subset of the total number of WFs. If `slwf_num` is equal to `num_wann` then what you do is simply the standard Marzari-Vanderbilt minimisation, i.e. you will generate a set of `num_wann` MLWFs. So in principle `slwf_num` can be equal to `num_wann` but that means that no selective localisation is performed, that's why the condition in the if statement has `.lt.` and not `.le.`. I'll fix the sentence in the user manual, and I'll explain better what happens when `slwf_num = num_wann`.
