### ISSUE TITLE
How to set the spin-quantization axis along the X-axis in wannier90?

### ISSUE THREAD

**Issue by Matephysics** [wannier-developers/wannier90#263]
Hi all,
I am a new user of wannier90 package. I am interested to calculate the Chern number for in-plane magnetization case say along the x-axis. For this, first of all, I performed the vasp calculations by setting the spin quantization axis to be (100). Now I want to project my DFT bandstructure to wannier. But I am confused about how to set the spin quantization axis along the x-axis in wannier90 package. I need your help in this regard.
Thank You in advance

**Comment by Chengcheng-Xiao** [comment]
@Matephysics 
Current release of VASP (v 5.4.4) does not support Wannier90 v2.0 and up.
Even if the CPP flag `VASP2WANNIER90v2` is set [[link]](https://cms.mpi.univie.ac.at/wiki/index.php/Installing_VASP#For_the_interface_to_Wannier90_.28optional.29).
If you look at `./src/symbol.inc` you will find 
```
!
! for the VASP2WANNIER90 interface
!
#ifdef VASP2WANNIER90v2
#define VASP2WANNIER90
#endif
```
Which means `VASP2WANNIER90v2` is automatically reset to `VASP2WANNIER90`.

I suggest you consider [Quantum espresso](https://www.quantum-espresso.org/) as your DFT calculator. Since its interface to Wannier90 ["pw2wannier90"](https://github.com/wannier-developers/wannier90/tree/develop/pwscf) is usually released alongside the Wannier90 package.

**Comment by giovannipizzi** [comment]
Closing as Wannier90 supports the choice with the flags mentioned. You should contact the VASP developers to ask to support it also in their interface.
