### ISSUE TITLE
Bug in restart logic (when writing checkpoint file)

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#278]
From the analysis of a report of Robert Peyton Cline:
restart seems to work only if a small `num_iter` is set so that the code stops before being killed by the scheduler, otherwise the code claims to be restarting but it starts from the very initial spreads.

By looking into the code I fear that now in the parallel code we always update only `u_matrix_loc`  during Wannierisation (see `internal_new_u_and_m`), and therefore until the end of a complete loop (i.e. at convergence or after `num_iter`) the `u_matrix` is not updated. `u_matrix` is only updated *after* a complete loop:
https://github.com/wannier-developers/wannier90/blob/develop/src/wannierise.F90#L633-L635

However the `write_chkpt` uses the `u_matrix` as the source of information.
Therefore, all checkpoints written before completion are actually still storing the very initial `u_matrix`.
This might explain why the restart works if one puts a small `num_iter`: the code updates `u_matrix` in memory after `num_iter` is surpassed and before stopping, and therefore also updates with the correct `u_matrix` on the checkpoint file.

**Comment by giovannipizzi** [comment]
The only easy way to do this is to gather the matrix before calling the write_chkpt. We don't need also to distribute it since only the root node needs it (to double check but it should be so: gather sends the matrix to the root node).

How do we want to do this? Should we call the gather routine inside wann_main, just before calling write_chkpt? I think this is the better way of doing it (the other option would be to have e.g. write_chkpt call the gathering routines, but this might be the wrong thing to do depending on which part of the code we are coming from).

We should also check if the same problem is present for the U_matrix_opt in the case of disentanglement and if there are other quantities that might be affected as well.

Moreover we should check the gamma_only case (but that one is not parallel, right?)

**Comment by hjunlee** [comment]
First, during the disentanglement, the checkpoint file is not written; only when finishing the disentanglement, it is written (done in wannier_prog.F90).

Second, in our parallelization scheme (k point parallelization), the parallel calculation with gamma_only=.true. doesn't make sense.

Third, among the quantities stored in the checkpoint file, only u_matrix and m_matrix are distributed in the case of parallelization. (currently, u_matrix_opt is not distributed).
So, I agree with you that the easy and simple solution is just to add the mpigather like below:
(of course, this is not an efficient solution)

(before)
if (ldump .and. on_root) call param_write_chkpt('postdis')

(after)
if (ldump .and. on_root) then
    call comms_gatherv(m_matrix_loc, num_wann*num_wann*nntot*counts(my_node_id), &
                       m_matrix, num_wann*num_wann*nntot*counts, num_wann*num_wann*nntot*displs)
    call comms_gatherv(u_matrix_loc, num_wann*num_wann*counts(my_node_id), &
                       u_matrix, num_wann*num_wann*counts, num_wann*num_wann*displs)
     call param_write_chkpt('postdis')
endif

Lastly, in this case, there remains one problem:
Currently, the subroutine param_chkpt_dist doesn't send m_matrix from the root node to other nodes. I guess that this subroutine is adopted from the similar routine in postw90. In that case, we don't need to send m_matrix since m_matrix is not necessary.
But, in order to restart correctly from the wannierization step, we need to send m_matrix.

Thus, we need to comment out the following lines:
!    if (.not.on_root .and. .not.allocated(m_matrix)) then                                                                                                                           
!       allocate(m_matrix(num_wann,num_wann,nntot,num_kpts),stat=ierr)                                                                                                               
!       if (ierr/=0)&                                                                                                                                                                
!            call io_error('Error allocating m_matrix in param_chkpt_dist')                                                                                                          
!    endif                                                                                                                                                                           
!    call comms_bcast(m_matrix(1,1,1,1),num_wann*num_wann*nntot*num_kpts)

Hyungjun Lee
