### ISSUE TITLE
The project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [wannier-developers/wannier90#285]
Please see how the Arch linux port installs the files: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wannier90

This is supposed to be done by your makefiles.

**Comment by qiaojunfeng** [comment]
I redownloaded the latest release v3.0.0 and ran `make all`, the code compiled without error. So the problem is not caused by makefile in this repository. I think the problem is related to your compiler configurations. 

Also, I confirmed that using the PKGBUILD in the AUR, it compiled and installed without error in my Archlinux. Can you paste your console output when running `makepkg` or `yaourt` or something like that?

**Comment by yurivict** [comment]
@qiaojunfeng I think you misinterpreted my message.

It does build, but your makefile doesn't install anything after it builds it.

**Comment by qiaojunfeng** [comment]
Yes, currently the `makefile` doesn't have any mechanism to install binaries, like `make install`. The installation is handled by the PKGBUILD.

**Comment by yurivict** [comment]
> Yes, currently the makefile doesn't have any mechanism to install binaries, like make install.

Please add this to Makefile.

PKGBUILD only exists on the Arch linux, others need to write the installer manually.

**Comment by qiaojunfeng** [comment]
@giovannipizzi Maybe we should update the build system? e.g. using the GNU configure and build system (`./configure --prefix=...; make; make install`)?

**Comment by giovannipizzi** [comment]
@qiaojunfeng I don't know if we really need to setup a configure system, it's maybe too much for such a simple set of dependencies. It's ok to add a make install.
However I understand that the typical way of choosing where to install is in the `configure` step, so if you know how to write a (possibly simple) configure script, it should be ok to prepare a PR with this. 
Maybe we could at this stage use this also to simplify the Makefile, that is pretty complex because before v3.0 only postw90.x was parallel and not wannier90.x, while now this is not the case anymore.

@qiaojunfeng let me know if you plan to work on this so if you have design questions I can provide feedback.

**Comment by yurivict** [comment]
> However I understand that the typical way of choosing where to install is in the configure step

No. Makefile is fully capable of installing by itself,
Please use the "install" command to install from your working/build directory into ```$(DESTDIR)$(PREFIX)/{bin/include/lib/...}```.

**Comment by giovannipizzi** [comment]
Thanks @yurivict for the comment. So one can assume, in `make install`, that `$(PREFIX)` is properly set, and just issue the correct `cp` commands?
If this is enough, adding an `install` command should be straightforward (one just needs to copy a few executable files, if built, to the `$(PREFIX)/bin` folder).

**Comment by yurivict** [comment]
Makefile should begin with
```
PREFIX ?= /usr
```
This is enough for the ```install``` target to work correctly.

**Comment by qiaojunfeng** [comment]
> Maybe we could at this stage use this also to simplify the Makefile, that is pretty complex because before v3.0 only postw90.x was parallel and not wannier90.x, while now this is not the case anymore.

@giovannipizzi I recalled that my previous effort on OpenMP parallelization would make the build system more complex, maybe we can tidy up the `Makefile` and possibly write a `configure` script when we start implementing OpenMP? 

Right now I just modified the `Makefile` to install the binaries to `/usr/bin/` & `/usr/lib/`
https://github.com/wannier-developers/wannier90/compare/develop...qiaojunfeng:make_install
This satisfies our basic need.
