### ISSUE TITLE
Issue in formatted spn format

### ISSUE THREAD

**Issue by giovannipizzi** [wannier-developers/wannier90#293]
From an email to the mailing list by Marten Richter:

Dear Wannier90 list,

for some reasons, I tried to use gw stuff from yambo with wannier and I 
also needed spins.
I need to use the spn formatted option, since I am too stupid (or lazy) 
to install the python package for FortranFile on the cluster.
So I tried to run gw2wannier90.py from the utility folder using spn 
output with spn_formatted.

I ran into several issues and I am really wondering, if the spn 
formatted output was tested.
Anyway I made a patch and I would be glad, if someone can look over it 
(who has reference data for the unformatted option for testing)
and could integrate it.
(Special care necessary, since I can write in several programming 
languages but not in python and I do not have really much data to check 
the correct behaviour).

[spnfix.patch.txt](https://github.com/wannier-developers/wannier90/files/3669896/spnfix.patch.txt)

**Comment by giovannipizzi** [comment]
Note: I didn't test if this applies to the latest version too.

**Comment by martenrichter** [comment]
I used the wannier90 shipped with quantum espresso 6.4.1, so 3.0.0. But it did not appear to be different to the recent git.

Marten

**Comment by qiaojunfeng** [comment]
Hi Marten, thanks for your patch!
I checked and tested on the example23 (with spin-orbit coupling included), the patched `gw2wannier90.py` worked correctly when transforming `spn` files, both formatted and unformatted. 

A minor suggestion: it's better not print the large SPN matrix: in your patch line 17, `print(SPN)`
Could you please create a pull request so the patch can be merged? Or I can help create the pull request if you prefer.

Other issues related to `gw2wannier90.py`: 
1. The script uses tab and space simutaneously, we should only use space or tab.
2. It worked correctly on unformatted file in my test case. But the [`scipy.io.FortranFile`](https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.io.FortranFile.html
) module doesn't guarranteed to work in all cases. The [`w90spn2spn.x`](https://github.com/wannier-developers/wannier90/blob/develop/src/w90spn2spn.F90) program (the corresponding documentation locates in the last of [this Tex file](https://github.com/wannier-developers/wannier90/blob/develop/doc/user_guide/utilities.tex
)) can be used to handle those cases. We can update the documentation of `gw2wannier90.py`.
3. Since python 2 will be deprecated, the script should be updated to python 3, `k_mapper.py` should be updated as well.

**Comment by martenrichter** [comment]
Hi Junfeng,
it would be nice, if you could create the pull request. The print(SPN) was  included by accident, it was used for debugging.

Marten

**Comment by qiaojunfeng** [comment]
Fixed in #294
