### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by LecrisUT** [wannier-developers/wannier90#443]
Is it GPLv2 or GPLv2-or-later. The license file provided as is, allows for either case and usually projects have to specify, e.g. in `README.rst` if they allow usage for later versions.

**Comment by mostofi** [comment]
Thanks for the comment/question. It's GPLv2 (because we don't explicitly specify "or later"). We hope to release the next version of the code under a more permissive license (LGPLv2.1 or later).

**Comment by jme52** [comment]
Dear @mostofi ,

This is very confusing. I recently looked into this, since we were concerned about the compatibility of the licenses of Wannier90 and SIESTA, and I found that:

- the Licence section of the [Wannier90 User Guide](https://github.com/wannier-developers/wannier90/raw/v3.1.0/doc/compiled_docs/user_guide.pdf) states that:

    > All the material in this distribution is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

- the welcome banner that Wannier90 prints states that:
    > This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version

Both of these texts can be traced back to commits in April 2006, so they pre-date the original v1.0 release of Wannier90.  This led us to believe that Wannier90 is and has always been GPLv2-or-later. Could you clarify why these two texts are not relevant?

Thank you.

**Comment by mostofi** [comment]
Thanks for that. Indeed it is a bit ambiguous. I am personally happy for you to take whichever interpretation you are comfortable with. As noted above, we do intend to clarify and resolve the issue in the next major release by applying a more permissive license.

**Comment by LecrisUT** [comment]
@mostofi, let's keep this issue open until the re-licensing is done. I want to have somewhere to subscribe about this for packaging to Fedora
