### ISSUE TITLE
IEEE_denormal exception with spinors = true

### ISSUE THREAD

**Issue by greschd** [wannier-developers/wannier90#72]
Hi all,

I got a strange error while playing around with the ``postproc_setup`` mode: When I set ``spinors = true`` in an input file for Bi, I get an IEEE_denormal exception. The program doesn't crash, but instead the .nnkp file contains invalid output (``***`` instead of a number).

I can look into where the exception comes from, but I'd be glad if you could tell me if there's something obviously wrong with my input file. In that case we should just add some test to the input parsing section and throw a nicer error.

[wannier.nnkp.txt](https://github.com/wannier-developers/wannier90/files/521163/wannier.nnkp.txt)
[wannier.win.txt](https://github.com/wannier-developers/wannier90/files/521164/wannier.win.txt)
[wannier.wout.txt](https://github.com/wannier-developers/wannier90/files/521165/wannier.wout.txt)

**Comment by giovannipizzi** [comment]
I remember that there was an issue with random projections and spinors, I think one of the variables is not initialised and therefore contains garbage (which I think is at the origin both of the IEEE_denormal and of the ***). 
Apparently, this was never fixed? There might be some message in the mailing list related to this. Anybody else remembers where the problem is exactly?

**Comment by jryates** [comment]
On 11 Oct 2016, at 08:43, Giovanni Pizzi <notifications@github.com> wrote:

> I remember that there was an issue with random projections and spinors, I think one of the variables is not initialised and therefore contains garbage (which I think is at the origin both of the IEEE_denormal and of the ***). 
> Apparently, this was never fixed? There might be some message in the mailing list related to this. Anybody else remembers where the problem is exactly?

In parameters.F90 there are two conditional blocks of code dealing with random projections. Search for the comment
! check there are enough projections and add random projections if required

I think the issue is that we don�t give proj_s an explicit value. It�s not completely clear to me what the best thing to do it:
1-   Choose it to be -1 or 1 based on random numbers
2-  Set half up and half down
     My thought it that in most cases we don�t know the angular character of the states we want (hence random) - but we probably do know the spin character. If we had a AFM with say 3 mostly up and 5 mostly down and the projection was onto 4 up and 4 down then I think this will cause numerical problems.
 Perhaps for the moment we code 2 (as the simplest), and if people find problems then we will code an improved version (it would need something extra passed in the win file to do this). I don�t have time to code and check this right now - so maybe one of you will get there before me.

 Jonathan


-- 
Department of Materials, University of Oxford, Parks Road, Oxford, OX1 3PH, UK
tel: +44 (0)1865 612797                http://users.ox.ac.uk/~oums0549/

**Comment by greschd** [comment]
Ok, I'll look into it. I'll write again if I need some help.

**Comment by greschd** [comment]
I fixed the garbage output in the .nnkp file by setting proj_s to alternate between +1 and -1. However this doesn't affect the IEEE_denormal, which still appears. I'll check to see where this comes from -- maybe it is harmless?

**Comment by greschd** [comment]
The denormal signal comes from writing 

    proj_s_qaxis(1,i),proj_s_qaxis(2,i),proj_s_qaxis(3,i)

I'm guessing that's because the quantization axis also needs to be set, right? What's a good value for this?

**Comment by greschd** [comment]
Another question: When the projections are only partially random, the random parts are initialized, but have ``proj_s = 0`` and ``proj_s_qaxis = 0., 0., 0.``. Does this make sense or should it also be set in the same way as when all projections are random?

**Comment by greschd** [comment]
The proposal I have now in the pull request alternates between +1 and -1 in both random and partially random projections, and the quantization axis is always z (0., 0., 1.). I restructured the code a little bit such that the initialization for partially random and fully random are handled by the same block.
